import { Router, type IRouter } from "express";
import adminProjectsRouter from "./admin-projects";
import adminRequestsRouter from "./admin-requests";
import adminTasksRouter from "./admin-tasks";
import assistantRouter from "./assistant";
import authRouter from "./auth";
import clientProjectsRouter from "./client-projects";
import clientRequestsRouter from "./client-requests";
import contactRouter from "./contact";
import coursesRouter from "./courses";
import dashboardRouter from "./dashboard";
import healthRouter from "./health";
import invoicesRouter from "./invoices";
import paymentRequestsRouter from "./payment-requests";
import portfolioRouter from "./portfolio";
import scriptsRouter from "./scripts";
import supportRouter from "./support";
import systemsRouter from "./systems";
import tasksRouter from "./tasks";

const router: IRouter = Router();

router.use("/auth", authRouter);
router.use(assistantRouter);
router.use(contactRouter);
router.use(clientRequestsRouter);
router.use(clientProjectsRouter);
router.use(coursesRouter);
router.use(adminRequestsRouter);
router.use(adminProjectsRouter);
router.use(adminTasksRouter);
router.use(scriptsRouter);
router.use(portfolioRouter);
router.use(invoicesRouter);
router.use(paymentRequestsRouter);
router.use(supportRouter);
router.use(systemsRouter);
router.use(tasksRouter);
router.use(dashboardRouter);
router.use(healthRouter);

export default router;
